name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.1
  ionicons: ^0.2.2
  url_launcher: ^6.3.0

  geolocator: ^11.0.0
  geocoding: ^3.0.0

  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/data/
    - assets/
